# Generated by Django 5.2.11 on 2026-02-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'технология стека',
                'verbose_name_plural': 'технологии стека',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('category', models.CharField(choices=[('python_basics', 'Основы Python'), ('git_github', 'Git и GitHub'), ('api', 'API веб-сервисов'), ('layout', 'Вёрстка'), ('django', 'Django-проекты'), ('bots', 'Чат-боты'), ('team', 'Командные проекты'), ('other', 'Другое')], db_index=True, default='other', max_length=20, verbose_name='категория')),
                ('category_order', models.PositiveSmallIntegerField(default=0, help_text='Чем меньше число, тем выше категория', verbose_name='порядок категории')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='изображение')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('demo_url', models.URLField(blank=True, help_text='Ссылка на работающий сайт / демо', verbose_name='демо')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('skills', models.ManyToManyField(blank=True, related_name='projects', to='skills.skill', verbose_name='навыки')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='projects.technology', verbose_name='технологии стека')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
                'ordering': ['-created_at'],
            },
        ),
    ]
