# Generated by Django 5.2.11 on 2026-03-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('python_basics', 'Основы Python'), ('git_github', 'Git и GitHub'), ('api', 'API веб-сервисов'), ('layout', 'Вёрстка'), ('django', 'Django-проекты'), ('bots', 'Чат-боты'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('async', 'Асинхронное программирование'), ('team', 'Командные проекты'), ('other', 'Другое')], db_index=True, default='other', max_length=20, verbose_name='категория'),
        ),
    ]
