# Generated by Django 5.2.11 on 2026-02-17 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('slug', models.SlugField(help_text="Уникальная строка для адреса страницы, например 'about'", unique=True, verbose_name='URL-идентификатор')),
                ('content', models.TextField(blank=True, verbose_name='содержимое')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'страница',
                'verbose_name_plural': 'страницы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pages/', verbose_name='изображение')),
                ('caption', models.CharField(blank=True, help_text='Необязательная подпись под фото', max_length=200, verbose_name='подпись')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.page', verbose_name='страница')),
            ],
            options={
                'verbose_name': 'изображение страницы',
                'verbose_name_plural': 'изображения страницы',
                'ordering': ['order'],
            },
        ),
    ]
