# Generated by Django 5.2.11 on 2026-02-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('category', models.CharField(choices=[('lang', 'Языки программирования'), ('fw', 'Фреймворки'), ('db', 'Базы данных'), ('tools', 'Инструменты'), ('libraries', 'Библиотеки'), ('devops', 'DevOps и инфраструктура'), ('bot', 'Боты и API'), ('other', 'Теория и Soft Skills')], default='other', max_length=20, verbose_name='категория')),
                ('category_order', models.PositiveSmallIntegerField(default=0, help_text='Чем меньше число, тем выше категория', verbose_name='порядок категории')),
                ('level', models.CharField(choices=[('1', 'Знакомство'), ('2', 'Начальный'), ('3', 'Средний'), ('4', 'Продуктивный')], default='2', max_length=1, verbose_name='уровень')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL-идентификатор')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='skills/icons/', verbose_name='иконка')),
            ],
            options={
                'verbose_name': 'навык',
                'verbose_name_plural': 'навыки',
                'ordering': ['category', 'name'],
            },
        ),
    ]
